### ISSUE TITLE
> contract binary not set. Can't deploy new instance.

### ISSUE THREAD

**Issue by shrugs** [nomiclabs/buidler#10]
## Issue

I'v encountered this twice when trying to produce bytecode for certain contracts.

```solidity
pragma solidity ^0.4.24;

import "zos-lib/contracts/upgradeability/AdminUpgradeabilityProxy.sol";


contract CustomAdminUpgradeabilityProxy is AdminUpgradeabilityProxy {
  bytes32 private constant ADMIN_SLOT = keccak256("org.zeppelinos.proxy.admin.custom");
}
```

this produces an artifact with valid abi, but an empty string `bytecode` property.

## Expected Behavior

bytecode should be produced

**Comment by shrugs** [comment]
Actually, maybe this isn't expected behavior; truffle doesn't produce this bytecode either (although for some reason I thought it did). Any ideas?

**Comment by alcuadrado** [comment]
Thanks for reporting this! Compiling that contract should produce a bytecode. I digged dipper into this issue and I think it is a bug in `solc`. I'm opening an issue in their repo, and leaving this one open for now.

**Comment by shrugs** [comment]
@alcuadrado actually this was my fault! sorry I forgot to update this issue!

I hadn't explicitly inherited from the parent contract, so no bytecode was produced. it's expected behavior

**Comment by alcuadrado** [comment]
Wait, no, this is the expected behavior 😅

It's easier to understand it with a minimal reproduction source code:

```solidity
pragma solidity 0.4.24;

contract Proxy {
    function _implementation() internal view returns (address);
}

contract UpgradeabilityProxy is Proxy {
    constructor(address _implementation) public {
    }

    function _implementation() internal view returns (address) {
        return address(0);
    }
}

contract CustomAdminUpgradeabilityProxy is UpgradeabilityProxy {
}
```

`UpgradeabilityProxy`'s constructor expects a param, and `CustomAdminUpgradeabilityProxy` doesn't override it, so the contract is abstract. This behavior is documented [here](https://solidity.readthedocs.io/en/latest/contracts.html#arguments-for-base-constructors).

**Comment by alcuadrado** [comment]
Yes, I figured it out when creating that reproduction code.
