### ISSUE TITLE
Move everything Ethereum related out of `src/core`

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#182]
This is a small refactor that will make a clear separation between what's Buidler's core (the task runner and the Buidler Runtime Environment), and what's its Ethereum integration.

This should be really straightforward, but feel free to ping me if you want to discuss how to do this.

**Comment by fvictorio** [comment]
Still relevant? Also I guess this is issue is pre-monorepo, is the description still accurate?

**Comment by alcuadrado** [comment]
I don't think this makes sense now. Buidler has a much broader and ethereum-specific scope.
