### ISSUE TITLE
Getting the imports of a file sometimes throws

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#206]
We are using solidity-parser-antlr, when the file is invalid the errors it can fail, as reported in https://github.com/federicobond/solidity-parser-antlr/issues/28

**Comment by fvictorio** [comment]
Is this still relevant with the parser's fork?

**Comment by alcuadrado** [comment]
Not sure if this still happens or not, but we implemented a default regexp-based imports extraction algorithm that's used when the parser fail. This issue isn't relevant anymore.
