### ISSUE TITLE
LocalAccountProvider throws when using the suggested network's accounts config

### ISSUE THREAD

**Issue by itirabasso** [nomiclabs/buidler#248]

**Comment by alcuadrado** [comment]
Can you clarify this? What's "the suggested network's accounts config"?

**Comment by itirabasso** [comment]
I meant the one in the [default-config](https://github.com/nomiclabs/buidler/blob/master/packages/buidler-core/src/internal/core/config/default-config.ts#L18)

I think the issue is [here](https://github.com/nomiclabs/buidler/blob/master/packages/buidler-core/src/internal/core/providers/construction.ts#L72), LocalAccountProvider expects to receive a string[] but the network's accounts config is AutoNetworkAccount[].

**Comment by alcuadrado** [comment]
I see, thanks for the clarification. That's probably the case.

**Comment by alcuadrado** [comment]
The accounts in default-config are supposed to be used in an automatic network. We don't have such a feature now, so I removed them.
