### ISSUE TITLE
Plugin for Ganache

### ISSUE THREAD

**Issue by daniel-iobuilders** [nomiclabs/buidler#259]
I would like to start to work on a plugin to manage Ganache. Could you give me some hints, what's the best way to start with the plugin?

**Comment by alcuadrado** [comment]
Hey Daniel! Thanks for offering your help 🙌🏻

We've been thinking about how to implement this. The main issue we see is that there's not a finished standard about what a javascript ethereum provider should be. There's [EIP1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) but it's not ready yet. This complicates integration with the different plugins (e.g. buidler-ethers and buidler-web3).

What we have in mind, as a temporal solution, is to implement something similar to [this script](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/scripts/test.sh).

The idea is to override the `test` task to do this:
1. Check if the network is `develop`. If it's not, do nothing special.
2. Check if ganache-cli is running in the right port, if it's running, do nothing special.
3. Start ganache-cli as a subprocess.
4. Wait for ganache-cli to start working (the linked script does it with `nc`).
5. Run the tests 
6. Gracefully kill ganache-cli.

What do you think?

I've just pushed [a branch](https://github.com/nomiclabs/buidler/tree/ganache-cli/packages/buidler-ganache) with an empty plugin with all of its boilerplate ready. You should be able to implement this in its [index.ts](https://github.com/nomiclabs/buidler/blob/ganache-cli/packages/buidler-ganache/src/index.ts), and to test it [here](https://github.com/nomiclabs/buidler/blob/ganache-cli/packages/buidler-ganache/test/tests.ts).

Also, I created a [CONTRIBUTING.md file](https://github.com/nomiclabs/buidler/blob/master/CONTRIBUTING.md) with some info about our dev workflow.

You may also want to check out [this guide](https://buidler.dev/documentation/#plugin-development-best-practices)

**Comment by fzeoli** [comment]
any updates?

**Comment by daniel-iobuilders** [comment]
@fzeoli Yes! I have working on it and opened a [draft pull request](https://github.com/nomiclabs/buidler/pull/281) for it. It's still a draft because I'm not sure how to test the the test task. I've written a test for, which executes a dummy tests, but I don't get any more feedback than that.
So I would need some help to properly test this.

**Comment by alcuadrado** [comment]
This plugin has finally been released today.

Thanks @daniel-iobuilders for your help!
