### ISSUE TITLE
Ganache gas estimation is wrong and tests OOG with V5 plugin

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/buidler#272]
Have been using buidler with `Ganache CLI v6.4.3 (ganache-core: 2.5.5)` and its gas estimation is wildly off - much lower than necessary. Because the V5 plugin relies on truffle-contract's gas estimation by default lots of calls fail. There are no problems when geth is the client. 

As a workaround I set a network with a gas value:
```
module.exports = {
  solc: { version: "0.5.5" },
  networks: {
    'development': {
      gas: 7000000
    }
  },
}
```
[Edit]
```
npx buidler test --network development
```

While debugging this I tried using a higher `gasMultiplier` in the config while logging the result in `getGasEstimate` at truffle-contract and it seemed like that option isn't being set. It's always 1.25. Not sure if this is a truffle bug or an issue here.

**Comment by alcuadrado** [comment]
> Have been using buidler with `Ganache CLI v6.4.3 (ganache-core: 2.5.5)` and its gas estimation is wildly off - much lower than necessary. Because the V5 plugin relies on truffle-contract's gas estimation by default lots of calls fail. There are no problems when geth is the client.

Do you have a project to reproduce this? I didn't find it. Maybe it's related to your ganache version.

> While debugging this I tried using a higher `gasMultiplier` in the config while logging the result in `getGasEstimate` at truffle-contract and it seemed like that option isn't being set. It's always 1.25. Not sure if this is a truffle bug or an issue here.

I think this is because of a name mismatch. `Buidler`'s default network is `develop`, not `development`. So you may have been setting the gas multiplier in another one.

Truffle used to use the name `develop`, and that's why it's called like that. I'm not sure if it's a good name, it can be confusing. What do you think?

**Comment by cgewecke** [comment]
Apologies I should have made a reproduction for this originally. Here is a repo that should show the problem.
+ https://github.com/cgewecke/ganache-estimation-bug

The example is cobbled together from the tests at the gas reporter and I don't know why estimation is a problem in this case. `ganache-cli` is latest (6.4.3)

Oh develop seems fine to me, makes sense.

**Comment by alcuadrado** [comment]
Thank you! That should be enough. I'll check it during the weekend.

**Comment by alcuadrado** [comment]
This is finally fixed 🎉

We now set the `gasMultiplier` to the `truffle-contract` instances (#292) and duplicate any gas estimation if ganache is being used (#296).

Thanks for reporting this! We'll release a new beta next week with these fixes :)

**Comment by cgewecke** [comment]
Thanks @alcuadrado!
