### ISSUE TITLE
Suggest pinning web3 when installing

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/buidler#273]
The docs for the truffle v5 plugin recommend `npm install web3@1.0.0-beta.37` but unless this is done using the `--save-exact` flag subsequent installations of a project (ex: in CI) will install higher versions and trigger:
```
Error BDLR802: Plugin @nomiclabs/buidler-truffle5 requires web3 version 1.0.0-beta.37 but got 1.0.0-beta.55.
If you haven't installed web3 manually, please run: npm install --save-dev web3@1.0.0-beta.37
If you have installed web3 yourself, please reinstall it with a valid version.
```
(This is a great error! Buidler's error management is excellent.)

**Comment by alcuadrado** [comment]
> The docs for the truffle v5 plugin recommend `npm install web3@1.0.0-beta.37` but unless this is done using the `--save-exact` flag subsequent installations of a project (ex: in CI) will install higher version

I can't believe `npm` doesn't default to `--save-exact` when you ask it to install an exact version 😩 Thanks for reporting this :)

> (This is a great error! Buidler's error management is excellent.)

Thank you! I'm glad you like it :)

**Comment by alcuadrado** [comment]
This has been fixed now :)

#304 includes a fix that adds `--save-exact` to that kind of errors.
#306 updates the docs and tutorials.
Also updated the installation instructions on our blog.

Thank you very much for all your feedback. We really appreciate it.
