### ISSUE TITLE
Feature: allow overriding plugins to define arbitrary cli flags

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/buidler#318]
Wrote my first buidler plugin and was (again) very impressed with:
+ how straightforward it was 
+ how well designed the plugin system is 
+ how nice the infrastructure for getting started is. 

This is a great architecture for tool builders. 

My [plugin](https://github.com/cgewecke/buidler-gas-reporter) is a simple override of `TASK_TEST_RUN_MOCHA_TESTS` which modifies the config passed to mocha and calls `runSuper`.

One thing I would have liked to do is to have the plugin be `off` by default (because it slows tests down and provides info you don't need to see on every run) but allow the user to toggle it on with a cli flag, e.g.
```
npx buidler test --gas
```

Because the `TEST_` tasks already define params this doesn't seem possible. It might be nice if plugins could extend BuidlerArguments arbitrarily for cases where they don't necessarily expect to be run by default - i.e when they expect to be optionally invoked as an addition to a commonly used built-in.

**Comment by alcuadrado** [comment]
Sorry for the late answer @cgewecke!

This is definitely something we will add :) We haven't implemented yet cause it has many edge-cases, and we don't want to release something broken.

Thanks for taking the time to create a plugin and for all your feedback.

**Comment by alcuadrado** [comment]
This has been implemented on #488. It will be released on Monday.
