### ISSUE TITLE
Feature: plugin badges

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/buidler#319]
If you have a utility which you make available as a buidler plugin (in addition to other integrations) it might be nice to have an official badge that advertises this. It can link to the project's buidler plugin repo which might have buidler specific info. 

Purely for example (generated at [shields.io](https://shields.io/), doesn't link to anything, I'm not an artist.):
```
![buidler](https://img.shields.io/static/v1.svg?label=buidler&message=plugin&color=FFA500&style=for-the-badge&logo=ethereum&labelColor=FFCC22)
```

![buidler](https://img.shields.io/static/v1.svg?label=buidler&message=plugin&color=FFA500&style=for-the-badge&logo=ethereum&labelColor=FFCC22)

**Comment by fzeoli** [comment]
I like this idea! I'll get our designer on it

**Comment by fzeoli** [comment]
Here it is 🤸‍♂️
[![buidler](https://buidler.dev/buidler-plugin-badge.svg?1)](https://buidler.dev)
`[![buidler](https://buidler.dev/buidler-plugin-badge.svg?1)](https://buidler.dev)`

**Comment by cgewecke** [comment]
Wow, beautiful! Thanks :)
