### ISSUE TITLE
OOM when compiling large projects

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#357]
When compiling large projects, Buidler can OOM and crash. To reproduce it, try compiling [Kyber's contracts](https://github.com/KyberNetwork/smart-contracts) with Buidler.

Running Buidler with `node --max-old-space-size=4096 node_modules/.bin/buidler` is a workaround, as it increases node's max heap size.

I found that Truffle [used to have the same issue](https://github.com/trufflesuite/truffle/issues/957) and they fixed it. We should investigate what they did. Maybe a launcher that sets that node flag? @cgewecke I saw you commented on that issue. Any idea how to solve this? :)

Thanks @anyhowclick for reporting it!

**Comment by cgewecke** [comment]
@alcuadrado I think it's still a problem at Truffle too ...  the underlying cause there was [running JSON.parse on the compiler output](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-compile/run.js#L254) which is still done. 

It *is* possible to address this by passing the compiler output string to a stream reader and composing the object piece by piece. [This](https://github.com/dominictarr/JSONStream) was a really popular solution.

**Comment by cgewecke** [comment]
There [was some controversy](https://www.theregister.co.uk/2018/11/26/npm_repo_bitcoin_stealer/) around that set of streaming libs, although AFAIK the json streamer was fine and [it continues to be heavily used](https://www.npmjs.com/package/JSONStream).

**Comment by alcuadrado** [comment]
Buidler 1.0.0 supports a `--max-memory` options that can be used in this case.

It is also documented here: https://buidler.dev/troubleshooting/common-problems.html#out-of-memory-errors-when-compiling-large-projects

Thanks @cgewecke and @Anyhowclick for your help :)
