### ISSUE TITLE
Support logs (getPastEvents, getPastLogs)

### ISSUE THREAD

**Issue by drortirosh** [nomiclabs/buidler#387]
unfortunately, `getPastLogs()` is not supported.
This is a major drawback, as our client code (even in testing) relies heavily on events

**Comment by alcuadrado** [comment]
Thanks for reporting this @drortirosh. Adding support for it is part of our immediate roadmap :)

**Comment by alcuadrado** [comment]
We just released [`v1.2.0` which includes full support for filters and subscriptions](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0).

Feel free to open a new issue if you find any problem with it.
