### ISSUE TITLE
Etherscan plugin uses hardcoded `artifacts` directory

### ISSUE THREAD

**Issue by rhlsthrm** [nomiclabs/buidler#388]
I changed my build artifacts directory to be `build/` which breaks this plugin. If I change the directory name to `artifacts/` it works. Looks like it could be coming from here:
https://github.com/nomiclabs/buidler/blob/master/packages/buidler-etherscan/src/index.ts#L59

Should be able to make it pull from the env config like the Ethers plugin does:

https://github.com/nomiclabs/buidler/blob/master/packages/buidler-etherscan/src/index.ts#L59

**Comment by alcuadrado** [comment]
Good catch Rahul! Thanks for reporting it. I submitted a PR fixing it and will release a patch version fixing it in the next few days.
