### ISSUE TITLE
Relative imports in contracts from subdirectories causing BDLR402 error code

### ISSUE THREAD

**Issue by CodeForcer** [nomiclabs/buidler#426]
I was just setting up Builder when I faced an error code which the documentation asked me to report:
```Error BDLR402: File /nathan/LocalCoinSwap/smart-contracts/ethereum-escrow/node_modules/@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Detailed.sol belongs to a library but was treated as a local one.```

I had a contract in a subfolder, with the following line which references an import from a node_module which was installed on a subdirectory level to my root Buidler installation:
```import "../node_modules/@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Detailed.sol";```

I was able to resolve the error and successfully compile by installing @openzeppelin/contracts-ethereum-package in my Buidler root directory, and then changing the import line to:
```import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Detailed.sol”;```

No big deal as I fixed it, but figured it was worth reporting as asked. I guess the issue the compiler had here is with the relative file path specification in imports, leading to this BDLR402 error

**Comment by alcuadrado** [comment]
This has been fixed in [`v1.2.0`](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0).

Please open a new issue if you think this error is still present.
