### ISSUE TITLE
Illegal import errors when using OpenZeppelin Contracts on Windows

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#437]
When trying to compile a project that uses OpenZeppelin Contracts you get unexpected Illegal Import errors that prevent you from compiling it.

Steps to reproduce it:

1. `npm i -D @openzeppelin/contracts` 
2. `npm i -D @nomiclabs/buidler`
3. `npx buidler` and create sample proyect
4. Add `import "@openzeppelin/contracts/ownership/Ownable.sol";` to `contracts/Greeter.sol`.
5. `npx buidler compile`.

**Comment by RickGriff** [comment]
I also have this problem for any contracts imported from the same directory as the target contract.

e.g, compiling _Greeter.sol_, with:

`import "./MyContract.sol";` 

I get:

```
contracts\Greeter.sol:9:1: ParserError: Source "MyContract.sol" not found: File import callback not supported
import "./MyContract.sol";
^------------------------^

Error BDLR600: Compilation failed
```

Contracts compile if all contracts are in the same .sol file.  Seems like an issue with the imports / path resolution.

I'm on Window 10, VSCode, and observe the problem when compiling contracts or running tests via Cmder (console emulator), Powershell, and WSL for command line.

**Comment by alcuadrado** [comment]
This has been fixed in [`v1.2.0`](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0).

Please open a new issue if you think this error is still present.

**Comment by michaelcohen716** [comment]
getting this issue on mac now
v 1.3.0
importing openzeppelin erc20 and getting `not found: File import callback not supported`

**Comment by ejwessel** [comment]
Bump
Mac
Persists on `Buidler version 1.3.4`
