### ISSUE TITLE
graphprotocol/graph-node fails with eth_getBlockByNumber doesn't support earliest nor pending

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/buidler#485]
found out that https://github.com/graphprotocol/graph-node is not working with buidlerevm
(it works fine witch ganache)

It at least fails when making a blockNumber request

Here is the log from buidlerevm when that happen :
```
eth_getBlockByNumber
  eth_getBlockByNumber doesn't support earliest nor pending
```

**Comment by alcuadrado** [comment]
I'm closing this issue, as it was fixed by @wighawag :)
