### ISSUE TITLE
Consider replacing web3 for ethers.js

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#5]
Most of buidler's instability comes from using web3, and in particular web3-provider-engine.

We should consider using [ethers.js](https://github.com/ethers-io/ethers.js/) instead. We could create an ethers-powered web3 shim if necessary.

I haven't had enough time to experiment on this yet, but I think it's a promising idea. Still, it would be a big change, so I'll like to get some feedback about it.

**Comment by federicobond** [comment]
I'm all for moving towards ethers.js as long as we provide compatibility with people using web3 too. Projects already on Truffle should be able to migrate their tests suites with relatively low friction.

**Comment by alcuadrado** [comment]
Agree! I created #6 to discuss how to approach that.

**Comment by alcuadrado** [comment]
I found this web3 compatibility layer already implemented by the author of ethers.js https://github.com/ethers-io/ethers-web3-bridge 🙌🏻

**Comment by alcuadrado** [comment]
We are migrating to ethers.js
