### ISSUE TITLE
Can't compile with an alternative solc version, list of solidity versions does not exist. 

### ISSUE THREAD

**Issue by minton1** [nomiclabs/buidler#525]
I was sold on trying out buidler from by the promises of stack traces, etc. However at the very first attempt at compiling, it's broken due to the solidity version list on github no longer existing or becoming inaccessible. 

Here is my config: 
```
import { BuidlerConfig } from "@nomiclabs/buidler/config";

const config: BuidlerConfig = {
  solc: {
    version: "0.5.16"
  },
  paths: {
    "artifacts": "app/src/contracts"
  }
};
export default config;

```

```
% npx buidler compile
Compiling...
Error BDLR502: Couldn't download compiler versions list. Please check your connection or use local version 0.5.15

For more info go to https://buidler.dev/BDLR502 or run Buidler with --show-stack-traces
```

Looking inside @nomiclabs/buidler/src/internal/solidity/compiler/downloader.ts
I see 
const COMPILER_FILES_DIR_URL =
  "https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/";

Going to that URL in chrome I get "400: Invalid request". 

This is not a great first experience, but thank you for buidling this! Im excited to try it out, Im currently stuck on an error that I need a stack trace for in my project.

**Comment by alcuadrado** [comment]
Hey @minton1! Thanks for reporting this!

Does this URL work for you? https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/list.json

**Comment by minton1** [comment]
Yes it does!

**Comment by minton1** [comment]
```
% npx buidler compile
Compiling...
Downloading compiler version 0.5.16
Compiled 47 contracts successfully
```

Github was having issues a few minutes ago, I think this was related. Thanks for your help!!

**Comment by alcuadrado** [comment]
It must have been that. I'm glad it's fixed!
