### ISSUE TITLE
--localhost parameter not recognized

### ISSUE THREAD

**Issue by jtremback** [nomiclabs/buidler#549]
Hi, I started a Greeter project using the normal steps, and am now working on integrating buidler-gas-reporter.

Following the instructions [here](https://buidler.dev/plugins/buidler-gas-reporter.html), I am trying to use `npx buidler test --localhost`, and seeing this error

```
✦2 ❯ npx buidler test --localhost
Error BDLR305: Unrecognized param --localhost

For more info go to https://buidler.dev/BDLR305 or run Buidler with --show-stack-traces

```

**Comment by alcuadrado** [comment]
Thanks for reporting this. That should be `--network localhost`.

**Comment by cgewecke** [comment]
@jtremback Sorry, that's my fault. There's a typo in the docs at buidler-gas-reporter, fixing rn.
