### ISSUE TITLE
tests error: "Transaction reverted for an unrecognized reason"

### ISSUE THREAD

**Issue by mcplums** [nomiclabs/buidler#554]
My tests have the error "Transaction reverted for an unrecognized reason. Please report this to help us improve Buidler" when calling an override function. 

Using buidler 1.3.2.

When running npx buidler tests, this line in my tests js:

`await shouldFail.reverting.withMessage(token.transferFrom(user,user1,2), "Only the contract can make transfers");`

This is the solidity function it is testing:

```
function transferFrom(address from, address to, uint256 tokenId) override public {
        require(false, "Only the contract can make transfers");
        from;
        to;
        tokenId;
    }
```

which is itself overriding the transferFrom function in the open zeppelin ERC721 contract.

Wat do?

**Comment by fvictorio** [comment]
I can't reproduce this. Do you have a public repo with this project?

Also, which version of `solc` are you using?

This is what I'm doing. Contract:

```solidity
pragma solidity ^0.6.5;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract MyCollectible is ERC721 {
    constructor() ERC721("MyCollectible", "MY721") public {
    }

    function transferFrom(address from, address to, uint256 tokenId) override public {
        require(false, "Only the contract can make transfers");
        from;
        to;
        tokenId;
    }
}
```

Test:

```
const { expect } = require("chai");

describe("MyCollectible", function() {
  it("transferFrom should fail", async function() {
    const MyCollectible = await ethers.getContractFactory("MyCollectible");
    const myCollectible = await MyCollectible.deploy();

    await myCollectible.deployed();

    await expect(myCollectible.transferFrom("0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1","0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1",2))
      .to.be.revertedWith('Only the contract can make transfers');
  });
});
```

I'm using a different assertion in the test, but that shouldn't make any difference.

**Comment by alcuadrado** [comment]
Thanks for reporting this, @mcplums. We released a new version of Buidler that addresses your problem.

Let us know if it is still present.
