### ISSUE TITLE
Bug: deployer not compatible with spread syntax

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/buidler#558]
```javascript
  // We get the contract to deploy
  const Greeter = await ethers.getContractFactory("Greeter");
  const args = ["Hello, Buidler!"];
  const greeter = await Greeter.deploy(...args);

  await greeter.deployed();

  console.log("Greeter deployed to:", greeter.address);
```

`TypeError: factory.deploy is not iterable (cannot read property Symbol(Symbol.iterator))`

**Comment by fvictorio** [comment]
This is very weird. The `...` syntax is, well, syntax, it shouldn't depend on the library.

Also, I initialized the sample project and tried your snippet and it worked fine. Do you have a full repo to reproduce the problem?

**Comment by thegostep** [comment]
It is probably the way I have my repository setup then. I am using a monorepo with https://github.com/PaulRBerg/create-eth-app

**Comment by fvictorio** [comment]
Any chance to make the repo public? Or to create a minimal example that reproduces the issue?

It's really strange if that snippet is giving you that error. I mean, in plain js it shouldn't happen, unless I'm missing something here.

**Comment by thegostep** [comment]
The issue was mine. Turns out I don't know js that well...
