### ISSUE TITLE
Docs for testing with ethers outdated (possibly)

### ISSUE THREAD

**Issue by PaulRBerg** [nomiclabs/buidler#587]
## Description
I'm new to TypeScript and Buidler, so I'm sorry if this is a false positive. While reading Rahul's [article](https://hackernoon.com/the-new-solidity-dev-stack-buidler-ethers-waffle-typescript-706830w0), I got stuck at this:

```ts
import { ethers } from "@nomiclabs/buidler";
```

It doesn't work - "ethers" cannot be found in builder's dist file. I checked the [buidler.dev docs](https://buidler.dev/guides/waffle-testing.html) and you're indicating to use the same "ethers" object (the import is in CommonJS form, but it doesn't matter).

## Screen Capture

<img width="922" alt="Capture d’écran 2020-05-20 à 03 24 35" src="https://user-images.githubusercontent.com/8782666/82391683-95d14a00-9a4a-11ea-974a-564a0814f648.png">

**Comment by alcuadrado** [comment]
Hey Paul,

I think you are missing the [type extensions file](https://github.com/nomiclabs/buidler/tree/master/packages/buidler-ethers#typescript-support) from your `tsconfig.json`.

`ethers` is not defined in `@nomiclabs/buidler`, but in the `@nomiclabs/buidler-ethers` plugin at runtime. When using TS, you need to let the compiler know about this. This is why you need the type extensions file.

Let me know if this solves your problem.

**Comment by PaulRBerg** [comment]
Wow, thank for the quick reply, Patricio!!

Oh right, I am indeed missing it. It's almost like I completely forgot about #586. There is really no way to include the type extensions without referencing "node_modules" in "tsconfig.json", is there?

Noob question, but couldn't there be a "@types/buidler-ethers" and "@types/buidler-waffle" package?

**Comment by PaulRBerg** [comment]
I hacked myself a way to include "node_modules" while still using yarn v2, but now I'm getting this:

<img width="917" alt="Capture d’écran 2020-05-20 à 03 49 01" src="https://user-images.githubusercontent.com/8782666/82392589-f5305980-9a4c-11ea-8e6a-15fe1608c533.png">

I'm using buidler@1.3.3 and ethereum-waffle@2.5.0 - maybe they are not compatible? I can see that the "getWallets" function expects a different type from the one provided by buidler's ethers.

**Comment by PaulRBerg** [comment]
**Update**: nevermind, I replaced "ethers" with "waffle" and it works like a charm now. I think this is either an error in Rahul's article, or his code is deprecated.

**Comment by alcuadrado** [comment]
> There's really no way to include the type extensions without referencing "node_modules" in "tsconfig.json", is there?

I tried to find a way to do this after you open #586, but I couldn't find one. It'd be great if there were some way to signal tsc to use node's module resolution. Something like `~@nomiclabs/buidler-ethers/...`.



> Noob question, but couldn't there be a "@types/buidler-ethers" and "@types/buidler-waffle" package?

I guess it could. But releasing a `@types/` package is much more cumbersone than your own. All of those live here: https://github.com/DefinitelyTyped/DefinitelyTyped

> I hacked myself a way to include "node_modules" while still using yarn v2

That's great. Can you explain it in #586? Thanks!

**Comment by PaulRBerg** [comment]
I'm going to close this since the docs are fine - it's just a matter of reading the [TypeScript guide](https://buidler.dev/guides/typescript.html).

FWIW, after opening this issue, I discovered that there is a way to import the types without referencing node_modules, and made a PR for that: https://github.com/nomiclabs/buidler/pull/589.
