### ISSUE TITLE
Better feedback when fallback and/or receive are missing in 0.6

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/buidler#596]
If a transaction isn't handled by the contract, the error is always that the fallback function is missing. After 0.6, the error can be more informative. For example:

- If the transaction has calldata and no value: "missing fallback function"
- If the transaction has calldata and value: "missing payable fallback function"
- If the transaction doesn't have calldata and value: "missing receive function"

With respect to the remaining case, when the transaction doesn't have nor calldata nor value, I don't know which function makes more sense to inform as missing. I'd say "receive", but I guess it's debatable.

**Comment by alcuadrado** [comment]
This is more complex than it seemed, so I created a table with all the relevant cases:



Transaction has calldata | Transaction has value | Contract has fallback | Fallback is payable | Contract has receive | Error
-- | -- | -- | -- | -- | --
Yes | Yes | Yes | Yes | --- | NO ERROR -- Uses fallback
Yes | Yes | Yes | No | --- | FALLBACK_NOT_PAYABLE_ERROR
Yes | Yes | No | --- | --- | UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR
  |   |   |   |   |  
Yes | No | Yes | --- | --- | NO ERROR -- Uses fallback
Yes | No | No | --- | --- | UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR
  |   |   |   |   |  
No | Yes | --- | --- | Yes | NO ERROR -- Uses receive
No | Yes | Yes | Yes | No | NO ERROR -- Uses fallback
No | Yes | Yes | No | No | Solidity 0.5: FALLBACK_NOT_PAYABLE_ERROR -- Solidity 0.6: **FALLBACK_NOT_PAYABLE_AND_NO_RECEIVE_ERROR**
No | Yes | No | --- | No | Solidity 0.5: UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR -- Solidity 0.6: **MISSING_FALLBACK_AND_RECEIVE_ERROR**
  |   |   |   |   |  
No | No | --- | --- | Yes | NO ERROR -- Uses receive
No | No | Yes | --- | No | NO ERROR -- Uses fallback
No | No | No | --- | No | Solidity 0.5: UNRECOGNIZED_FUNCTION_WITHOUT_FALLBACK_ERROR -- Solidity 0.6: **MISSING_FALLBACK_AND_RECEIVE_ERROR**

The "---" cells can be read as "both value"/"doesn't matter".

I think we should add the error types that are in **bold**.

What do you think, @fvictorio ?

**Comment by fvictorio** [comment]
I think the last two should be different, shouldn't them? The first one is _"You need to add a payable fallback or a receive function"_ and the second one is _"You need to add a fallback or a receive function"_  But the last one is a veeery edge case though, so I don't think this is too important.

Another minor nitpick is that maybe the error should be called `MISSING_FALLBACK_OR_RECEIVE_ERROR`.

Other than that, looks great.

**Comment by alcuadrado** [comment]
> I think the last two should be different, shouldn't them? The first one is _"You need to add a payable fallback or a receive function"_ and the second one is _"You need to add a fallback or a receive function"_ But the last one is a veeery edge case though, so I don't think this is too important.

Let's keep a single error. In the worst case, users will add a non payable fallback, rerun their tests and get a much more precise error.

> Another minor nitpick is that maybe the error should be called `MISSING_FALLBACK_OR_RECEIVE_ERROR`.

👌

**Comment by alcuadrado** [comment]
This has already been implemented
