### ISSUE TITLE
Bug: buidler-etherscan is not compatible with verifying contracts deployed from other contracts

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/buidler#606]
attempting to add compatibility with https://github.com/thegostep/solidity-create2-deployer

**Comment by fvictorio** [comment]
Is this a problem specific to `buidler-etherscan`? I mean, were you able to do this manually or with `truffle verify`, for example?

**Comment by thegostep** [comment]
Yes, it is possible to verify manually.

**Comment by fvictorio** [comment]
Hey @thegostep, I tried to reproduce this with a simple example and didn't have this problem. Maybe [this PR](https://github.com/nomiclabs/buidler/pull/416) fixed it? I'm not sure. I'm going to close this for now, but please re-open if this is still happening.
