### ISSUE TITLE
evm_increaseTime not working unless stand-alone?

### ISSUE THREAD

**Issue by simondlr** [nomiclabs/buidler#613]
Hey.

Using Waffle + buidlerevm to test. I want to run evm_increaseTime, but it doesn't work, unless I run buidlerevm as a stand-alone node. I'm using openzeppelin test helpers to increase the time. It works fine when running as a stand-alone node, but otherwise not.

I just get a: ```Error: Invalid JSON RPC response: ""```

Is this functioning as expected?

**Comment by alcuadrado** [comment]
I should work with the in process Buidler EVM. The standalone node is just
a wrapper around it.

Do you have a link to a repo to reproduce this?

**Comment by simondlr** [comment]
Unfortunately not ready yet to open source.

I'm recreating the simplest versions here:

buidler.config.js

```
const defaultAccounts = require("./scripts/wallet-utils.js");
const { usePlugin } = require('@nomiclabs/buidler/config');
usePlugin("@nomiclabs/buidler-waffle");

module.exports = {
  defaultNetwork: 'localhost',
  networks: {
    localhost: {
      url: 'http://localhost:8545',
    },
    buidlerevm: {
      accounts: defaultAccounts(),
    }
  },
  solc: {
    version : "0.6.6",
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
}
```

defaultAccounts is just and HD Wallet.

test

```
const { time } = require('@openzeppelin/test-helpers');

const { expect } = require("chai");

describe("timetest", function() {

  it('time fail', async () => {
    await time.increase(10); // 10 seconds increase.
  });

});
```

What was interesting. I noticed strange behaviour. When I was running a stand-alone, running tests using the in-process EVM, the 'increaseTime' call would send it to the stand-alone node, NOT the in-process EVM.

So not sure if it's config file related or whether increaseTime has a default RPC it's trying to connect to? Maybe it's due to my config?

**Comment by alcuadrado** [comment]
Hey @simondlr,

Thanks for posting more info about your problem.

This is some really unexpected behavior of `@openzeppelin/test-helpers`. It tries to use a globally available instance of `web3`. If it doesn't find one, it initializes a provider pointing to `localhost:8545`. 

You can use `@openzeppelin/test-helpers` by installing `@nomiclabs/buidler-web3` and `web3`, and adding `usePlugin("@nomiclabs/buidler-web3");` to your config.

Let me know if this worked.

**Comment by simondlr** [comment]
Thanks for helping to dig deeper. Unfortunately, I ran into new problems that I'm still trying to debug. I'm using yarn (forked from Austin's Scaffold-ETH), and ran into problems with buidler-web3 not being picked up.

I'm assuming it's related to this: https://github.com/nomiclabs/buidler/issues/570.

Will continue debugging.

**Comment by simondlr** [comment]
I eventually managed to fix the hoisting/dependency problem (moved it to the root): what was done here: https://github.com/austintgriffith/scaffold-eth/pull/5.

This works now. Appreciate the help. @alcuadrado. I'll close the issue.

**Comment by coostendorp** [comment]
In case it helps anyone, I ended up doing the following (using ethers5, waffle, buidler):
`
ethers.provider.send("evm_increaseTime", [60])   // add 60 seconds
ethers.provider.send("evm_mine")
`

**Comment by vnavascues** [comment]
@coostendorp Hey, I'm very grateful for your comment, what a hint!

I'm currently learning about smart contract development in Ethereum, and until now I've been using `JavaScript + Truffle + Web3 + Jest + OZ Test Environment + OZ Test Helpers`.
A few days ago I switched to `TypeScript (TypeChain) + Buidler + Ethers.js + Waffle (mocha/chain)` just for giving it a try, and I wasn't sure how I about manipulating the blocks/time on my tests. The learning curve with this new stack is quite step and I didn't want to end up installing all the Truffle-Web3-Ganache plugins for Buidler.
Today I had an aha moment about porting the `time` OZ Test Helper, so I inspected it and saw the `evm` manipulation... but of course using Web3 and for Ganache-cli. Nonetheless as soon as I saw your comment I connected the dots, checked the Budler EVM documentation, and ported the library (locally). It works!
To be honest I'm very looking forward for Waffle officially supporting Jest, and OZ supporting ethers.js.

Thanks

**Comment by antoncoding** [comment]
> In case it helps anyone, I ended up doing the following (using ethers5, waffle, buidler):
> 
> ```
> ...
> ethers.provider.send("evm_mine")      // mine the next block
> ```

While coding in typescript, I need to use this
```typescript
await (provider as any).send('evm_mine');
```
to avoid the following error. 

```
Error in plugin solidity-coverage: TSError: ⨯ Unable to compile TypeScript:
test/MyTest.ts:266:22 - error TS2554: Expected 2 arguments, but got 1.

266       await provider.send('evm_mine');
                         ~~~~~~~~~~~~~~~~

  node_modules/@ethersproject/providers/lib/web3-provider.d.ts:26:26
    26     send(method: string, params: Array<any>): Promise<any>;
                                ~~~~~~~~~~~~~~~~~~
    An argument for 'params' was not provided.
```

**Comment by fvictorio** [comment]
@antoncoding you can do `provider.send("evm_mine", [])` in that case to avoid the `any` casting.
