### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [nomiclabs/buidler#653]
It would be great if Builder provided support for deploying and upgrading diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by alcuadrado** [comment]
Hey @mudgen,

Thanks for suggesting this.

Buidler is very opinionated so this wouldn't be a good fit for it. This would be a great fit for a plugin though.

If you or anyone is interested in creating one, here's [a guide about how to do it](https://buidler.dev/advanced/building-plugins.html), and [here's a repo with all the needed boilerplate](https://github.com/nomiclabs/buidler-ts-plugin-boilerplate).

**Comment by fzeoli** [comment]
unopinionated* :P

**Comment by mudgen** [comment]
@alcuadrado Thank you!  Do you know anyone who might be interested in making a plugin for this?

**Comment by alcuadrado** [comment]
I'm not familiar with this EIP nor the Diamond standard, so I'm afraid not.

Creating plugins is incredibly simple though. We can give you some guidance if you feel like doing it.

**Comment by fzeoli** [comment]
Plenty of community members in our Telegram group are building plugins, so
you might be able to find someone there who wants to build it too
https://t.me/BuidlerSupport

**Comment by mudgen** [comment]
Thanks @alcuadrado and @fzeoli I appreciate it.  I'll check with the Telegram group.

**Comment by alcuadrado** [comment]
Hey @mudgen, I'm closing this issue as this already supported by `buidler-deploy`. Feel free to open a new one.
