### ISSUE TITLE
Running coverage with multiple --testfiles

### ISSUE THREAD

**Issue by alsco77** [nomiclabs/buidler#665]
### What

I am currently trying to migrate from a truffle project to Buidler -> https://github.com/mstable/mStable-contracts/pull/89

As you can see from the `buidler.config.ts`, the test suite is written in Typescript.

### Issue

Running `yarn buidler coverage --network coverage --solcoverjs ./.solcover.js --testfiles test/**/Test*.ts --show-stack-traces` results in the following output:

```
Error BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts

Error: BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts
    at ArgumentsParser._parsePositionalParamArgs (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:271:13)
    at ArgumentsParser.parseTaskArguments (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:113:38)
    at main (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:128:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Outcome

I tried running a simple test with one file and it works, so I must be missing something on the `--testfiles` flag.

Could someone help me with that? How can I specify multiple?

**Comment by alcuadrado** [comment]
I believe this is a bug in `solidity-coverage`. 

I think [this line](https://github.com/sc-forks/solidity-coverage/blob/master/plugins/buidler.plugin.js#L36) should read

```ts
    .addOptionalPositionalParam("testfiles",  ui.flags.file)
```

/cc @cgewecke

**Comment by cgewecke** [comment]
@alsco77 

Just published a patch for this (`0.7.9`). 

If you're still seeing problems with glob args after upgrading please feel free to ping solidity-coverage and will take another look.

Thanks @alcuadrado!

**Comment by alsco77** [comment]
Thanks for the quick turn around on this guys!

Just upgraded to `0.7.9` and tried running again, but still got the same output, seems like its still falling over on the second test. Could you confirm if my arg is being passed correctly?

```
buidler coverage --network coverage --solcoverjs ./.solcover.js --testfiles test/governance/TestClaimableGovernor.spec.ts test/governance/TestDelayedClaimableGovernor.spec.ts test/governance/TestGovernable.spec.ts test/integrations/TestMintWith1inch.spec.ts test/masset/TestBasketManager.spec.ts test/masset/TestMassetMinting.spec.ts test/masset/TestMassetRedeemMulti.spec.ts test/masset/TestMassetRedemption.spec.ts test/masset/TestMasset.spec.ts test/masset/TestMassetSwap.spec.ts test/nexus/TestNexus.spec.ts test/savings/TestSavingsContract.spec.ts test/savings/TestSavingsManager.spec.ts test/shared/TestCommonHelpers.spec.ts test/shared/TestInitializableModule.spec.ts test/shared/TestInitializablePausableModule.spec.ts test/shared/TestModule.spec.ts test/shared/TestPausableModule.spec.ts test/shared/TestStableMath.spec.ts test/upgradability/TestDelayedProxyAdmin.spec.ts --show-stack-traces
Error BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts

Error: BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts
    at ArgumentsParser._parsePositionalParamArgs (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:271:13)
    at ArgumentsParser.parseTaskArguments (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:113:38)
    at main (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:128:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cgewecke** [comment]
@alsco77 

Ah sorry, I "fixed" this by adding glob expansion handling because your example use was `--testfiles test/**/Test*.ts`. 
It looks like a list of files after the flag will need to be a separate thing. 

Do you want to close here and we can address in an issue at solidity-coverage? This is a bug in the plugin rather than anything at Buidler.

**Comment by alsco77** [comment]
My mistake @cgewecke, I can just wrap my command with single quotes (`--testfiles 'test/**/Test*.ts`). I have just tested that and it's working fine.

Possibly the docs in `solidity-coverage` could be updated to reflect that though :+1:
