### ISSUE TITLE
Inconsistent error messages when running `buidler test`

### ISSUE THREAD

**Issue by alsco77** [nomiclabs/buidler#666]
### Issue

When running `buidler test`, I am getting inconsistent error messages between local development and CI.

See failed build on CircleCI here -> https://app.circleci.com/pipelines/github/mstable/mStable-contracts/779/workflows/04af01d0-9f17-43a6-9094-f64c03ebff5b/jobs/782/steps

Running the same command (`yarn test`) locally shows tests passing.

```
package.json:

`test`: `...; yarn buidler test;`
```

I can't see why this would be happening, since in both circumstances it should be using the projects `buidler` version. I assume something is different about the `buidler evm`. Fwiw, I had some issues getting the tests to pass even on local

Edit: For some reason it works with neither `expectRevert.assertion` or `expectRevert.unspecified` - in the former it complains about 'invalid opcode', and in the later about 'revert'..

**Comment by alsco77** [comment]
Seems to be resolved now :man_shrugging: Will open back up if I can isolate my problem again :smile:

**Comment by fvictorio** [comment]
I was just looking into this, glad to see it works now! Let us know if it happens again.
