### ISSUE TITLE
How can I pass in `bytes` type constructor argument when verifying

### ISSUE THREAD

**Issue by NIC619** [nomiclabs/buidler#678]
The constructor of my contract takes in `bytes` type argument.
```solidity
constructor(bytes _input) {
    …
}
```

And for example when I pass in "0xabcdef" during contract deployment:
```JavaScript
const factory = await ethers.getContractFactory("MyContract");

// If we had constructor arguments, they would be passed into deploy()
let contract = await factory.deploy("0xabcdef");
```
It would treat the hex string as bytes, not string.

However when I run `npx buidler verify-contract --contract-name MyContract --address DEPLOYED_CONTRACT_ADDRESS 0xabcdef`, the argument `0xabcdef` would be treated as string and parsed as `3078616263646566` and the verification would fail because constructor arguments do not match.

**Comment by alcuadrado** [comment]
Hey @NIC619 

Can you help me understand your problem? What do you mean by "the argument 0xabcdef would be treated as string and parsed as 3078616263646566"?

Thanks

**Comment by NIC619** [comment]
Hi @alcuadrado . Thanks for the reply.

The constructor arguments will be abi encoded and send along with the contract verification request:
https://github.com/nomiclabs/buidler/blob/2a344636aea340ef927fd1409065829edde34bb1/packages/buidler-etherscan/src/index.ts#L76-L79

While during contract deployment(the `factory.deploy("0xabcdef")` code snippet in my previous comment), it was correctly encoded as `abcdef`.
However, it was encoded as `3078616263646566` when I append `0xabcdef` to `npx buidler verify-contract  --contract-name MyContract --address DEPLOYED_CONTRACT_ADDRESS `.
Which means, instead of treating it as hex string like `factory.deploy` did,  `AbiEncoder.encodeConstructor` treat `0xabcdef` as string of ascii characters(`3078616263646566` is the ascii representation of `0xabcdef`).

And that's why etherscan contract verification failed, as it was expecting constructor arguments to be `abcdef` but instead got `3078616263646566`.

Please let me know if it's still unclear. Thanks!

**Comment by alcuadrado** [comment]
Thanks for the clear explanation, @NIC619.

I'm afraid that this may be a limitation of the plugin, or a bug in the abi encoder. We'll need to investigate further. We'll let you know when we have updates.

**Comment by fvictorio** [comment]
Hey @NIC619, can you check if this works for you using the new version of the `buidler-etherscan` plugin?

**Comment by NIC619** [comment]
Hi @fvictorio , the new version works! Thanks a lot!
