### ISSUE TITLE
Getting OpenZeppelin's openzeppelin-solidity into a scaffold-eth project

### ISSUE THREAD

**Issue by wschwab** [nomiclabs/buidler#682]
Hi! I'm building (buidling?) a project using [scaffold-eth](https://github.com/austintgriffith/scaffold-eth), which in turn embeds Buidler in a create-eth-app (and does some other cool things).  The basic structure (that I need for this issue) is:
```
project
├── node_modules
│   └── openzeppelin-solidity
├── packages
│   ├── buidler
│   │       ├── contracts
│   │       └──  package.json
│   └── react-app
├── package.json
├── yarn.lock
```
There are calls to the `openzeppelin-solidity` package in the contracts located in `packages/buidler/contracts`. When I try to compile with the contracts pointing to `node_modules` in the project root, I get `BUIDL401: ... is outside the project`. I tried making a phony `node_modules` inside the `buidler` folder, and copying the contracts to there, but then I get `BUIDL402: File belongs to a library but was treated as a local one`. (The docs say to raise an issue if you get this error, so I figured I would, even if I got it because of an ugly hack I tried.)

I could copy the OZ contracts into the `contracts` folder I suppose, but figure that the library is popular enough that I should raise the issue. It could be that this is more of an issue with `scaffold-eth` than Buidler - I plan on raising it there, too.

What do you propose I do to get the contract calls to OpenZeppelin to work?

**Comment by alcuadrado** [comment]
Hey @wschwab,

Do you have a link to a repo so that we can reproduce this? Those errors you are getting are not expected.

**Comment by wschwab** [comment]
Hmm... it's a private repo, but I can try to recreate the issue. Might not get to it until later today or tomorrow morning, but I'll drop a link here if I do.

Thanks for the quick reply!

**Comment by wschwab** [comment]
Actually, I did it now instead. The repo is here: https://github.com/wschwab/scaff-zep-concept

It's a `scaffold-eth` setup, so after you clone, you could just use `yarn compile` and it'll use buidler to compile. 

Right now I have a contract `test.sol` pointing at OpenZeppelin contracts that I put in a mock `node_modules` in the `buidler` directory ('packages/buidler`). This was what gave me the BUIDL402 before, and did again when I tested it now. 

When I had it point at the OpenZeppelin contracts in the root `node_modules` I got the BUIDL401. If you'd like to test this yourself, edit the path in `packages/buidler/contracts/test.sol` by having the import go three directories up (right now it only goes one up):
```
../../../openzeppelin-solidity/contracts/token/ERC20/ERC20.sol
```
Thanks again!

**Comment by alcuadrado** [comment]
Thanks, @wschwab.

I just cloned the repo, run `yarn install --frozen-lockfile`, `yarn compile` and it worked.

Can you provide more info about:

* Your operating system and version
* Your node version
* Your yarn version

**Comment by wschwab** [comment]
OS: Debian 10 (latest)
Node: 12.16.1
Yarn: 1.22.4

**Comment by alcuadrado** [comment]
Oh, wait. The only Solidity file, `SmartContractWallet.sol` doesn't import anything from open zeppelin.

I added this, and it still works `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";`.

**Comment by wschwab** [comment]
A bit embarrassing, but I just realized I hadn't committed my changes before pushing - I had set something like that up. I just tested again and am still getting the errors, so I'll commit and push, though I'm getting the feeling it's some edge case by me and not Buidler.

**Comment by alcuadrado** [comment]
I'm getting 

```
Error BDLR407: File ../node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol, imported from contracts/test.sol, not found.
```

which seems fine, as `scaff-zep-concept/packages/buidler/node_modules` doesn't exist. I think this is because you are using yarn workspaces.

If I modify your contract so that the import looks like this:

```Solidity
import 'openzeppelin-solidity/contracts/token/ERC20/ERC20.sol';
```

it works.

**Comment by wschwab** [comment]
Ah, I see. The `.gitignore` has `node_modules` in it, so my hack of putting a new `node_modules` at that level didn't get pushed. I should've thought of that.

In any event, you hit the problem anyway: I've been using paths that include the path into `node_modules` instead of just calling the package by name. I'm not sure why specifying the whole path fails, but that fixes everything. I'll close, as this seems to fix any issue.

Just to reiterate in case someone else is having a similar problem. Don't import using:
```
import '../../../openzeppelin-solidity/contracts/token/ERC20/ERC20.sol';
```
import using:
```
import 'openzeppelin-solidity/contracts/token/ERC20/ERC20.sol';
```

Thanks for the help!
