### ISSUE TITLE
A problem with the current plugin resolution logic

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/buidler#685]
Plugins are loading using `usePlugin`, which internally has to resolve the plugin name into an npm package. 

This resolution is based on node's one and is implemented with `require.resolve(pluginName, {paths: [startingDir]})`. Currently, the `startingDir` is `<buidler-installation>/internal/core/plugins.ts`, except when Buidler is running on `EXECUTION_MODE_LINKED` mode, where the current working directory is used.

This can lead to problems when a monorepo is used, as you can easily end up with this in your filesystem:

```
/
  node_modules/
    @nomiclabs/buidler
  packages/
    a/
      buidler.config.js
      node_modules/
        plugin@v1
    b/
      buidler.config.js
      node_modules/
        plugin@vb
```

In this case, the plugins won't be found. To make things worse, yarn/lerna may hoist a version of the plugin, but not the other.

To fix this, I propose changing the `startingDir` in the resolution logic to:
* The CWD if executing on `EXECUTION_MODE_LINKED` mode.
* `<buidler-installation-path>` if globally installed.
* Buidler config's dir if locally installed.

This is probably related to #570 and possible to #468

**Comment by alcuadrado** [comment]
Note that this is also a problem with type extensions. We should consider using Paul's solution here, and start recommending triple slash references.

**Comment by kfichter** [comment]
Yeah this has started to cause us a bit of a headache. We're using `nohoist` right now, but that blows up our `node_modules` and means setting `private: true` (which has to be temporarily set to `false` whenever we publish a package). I'd be happy to make a pull request if this issue isn't a priority for the buidler team right now.

**Comment by alcuadrado** [comment]
Hey @kfichter. This was already fixed and will be released in the next few days.

**Comment by fvictorio** [comment]
@alcuadrado was this fixed in 1.4.5?

**Comment by alcuadrado** [comment]
It was!

**Comment by kfichter** [comment]
Amazing, thank you so much! 🤙🤙
