### ISSUE TITLE
Nested array of struct in calldata breaks EVM tracing

### ISSUE THREAD

**Issue by mikemcdonald** [nomiclabs/buidler#698]
```
  struct Trade {
        address dst;
        uint    amount;
  }

  function test(Trade[][] memory TradeSequence) { ... }
```

Causes an error `Buidler EVM tracing disabled: ContractsIdentifier failed to be initialized.` `TypeError: Cannot read property 'startsWith' of undefined`

**Comment by fvictorio** [comment]
Thanks for reporting! This was fixed by #774 and will be available in the next release. We'll comment here when the release is out.
