### ISSUE TITLE
Cannot fire events or call view functions using EVM

### ISSUE THREAD

**Issue by LPSCRYPT** [nomiclabs/buidler#704]
I believe that I have my provider and contract object formatted correctly, however an event listener for a function in my contract which requires gas never fires. Default listeners (such as 'block') work fine. Additionally, I always get a "WARNING: Calling an account which is not a contract" error in the EVM console whenever I call a view function. I am lead to think that the deployed contract and the client are not actually connected, so no events are firing and it can't view state through a view call, while still eating gas for other functions which have errors that don't display in the console. 

Here is the code by which I am assigning my contract object.
```javascript
let provider = new ethers.providers.Web3Provider(window.ethereum);
let signer = provider.getSigner(0);
let contractInstance = new ethers.ContractFactory(abi, bytecode);
let viewInstance = new ethers.ContractFactory(abi, bytecode);
let contractAddressSpecified = contractInstance.attach(
"0x7c2C195CD6D34B8F845992d380aADB2730bB9C6F");
let viewAddressSpecified = viewInstance.attach(
"0x7c2C195CD6D34B8F845992d380aADB2730bB9C6F");
let contractSigner = contractAddressSpecified.connect(signer);
let viewSigner = viewAddressSpecified.connect(provider);
```

I derive the contract address from a deploy script:
```javascript
	const provider = await new ethers.providers.JsonRpcProvider(
		"http://127.0.0.1:8545/"
	);

	const Contract = await ethers.getContractFactory("Contract");
	const deployContract = await Contract.deploy();

	await deployContract.deployed();

	console.log("Contract deployed to ", deployContract.address);
```

Then I call the contract like so:
```javascript
let ctm = await contractSigner.fireFunction("Input");
ctm = await ctm.wait();
console.log("receipt", ctm);
```

To which the transaction 'succeeds' based on the status of the tx receipt, but provides no further data and does not fire an event.

**Comment by alcuadrado** [comment]
> I derive the contract address from a deploy script:
> 
> ```js
> 	const provider = await new ethers.providers.JsonRpcProvider(
> 		"http://127.0.0.1:8545/"
> 	);
> 
> 	const Contract = await ethers.getContractFactory("Contract");
> 	const deployContract = await Contract.deploy();
> 
> 	await deployContract.deployed();
> 
> 	console.log("Contract deployed to ", deployContract.address);
> ```

How are you running this?

**Comment by LPSCRYPT** [comment]
> > I derive the contract address from a deploy script:
> > ```js
> > 	const provider = await new ethers.providers.JsonRpcProvider(
> > 		"http://127.0.0.1:8545/"
> > 	);
> > 
> > 	const Contract = await ethers.getContractFactory("Contract");
> > 	const deployContract = await Contract.deploy();
> > 
> > 	await deployContract.deployed();
> > 
> > 	console.log("Contract deployed to ", deployContract.address);
> > ```
> 
> How are you running this?

As a script on the EVM.

**Comment by alcuadrado** [comment]
Sure, but what's the exact command you are running?

My suspicion is that you do something like `npx builder run script.js`, which creates a temporal instance of Buidler EVM. While you are initializing a provider pointing to localhost, you are not using it.

The right way of running it would be `npx builder --network localhost run script.js`.

**Comment by LPSCRYPT** [comment]
You are correct. It's working, thanks! 

I should have also used 

```javascript
const Contract = await ethers.Contract("Contract");
``` 

instead of 

```javascript
const Contract = await ethers.getContractFactory("Contract");
```

Now I can access the event through the transaction receipt. However, the event for catching the event still isn't firing:

```javascript
provider.on("eventfired", (x) => {
					console.log("event: ", x);
				});
```

**Comment by alcuadrado** [comment]
> ```js
> ```js
> const Contract = await ethers.Contract("Contract");
> ```
> ```

This is definitely incorrect. I don't know what a contract would do if you just pass it a name.

**Comment by LPSCRYPT** [comment]
My bad, I must thrown quotes in there by mistake while formatting my post. Think of the Contract input as properly formatted with address, abi, and bytecode.

I managed to get both read and write functionality to work after adding the ```--network localhost``` flag to the contract deploy script. However, contract event listeners are not firing for some reason. The 'block' listener continues to fire with every new block.

**Comment by fvictorio** [comment]
Do events work if you use `contract.on("Event", () => {...})`?

See the "Listening on events" snippet [here](https://docs.ethers.io/v4/api-contract.html) for example (assuming you are using ethers v4, but v5 should have a similar API).

**Comment by LPSCRYPT** [comment]
I figured it out, I believe that in a previous version of the documentation the event name had to be in lower case, but with the latest version it works when it matches the case-sensitive name of the fired event. Thanks, all my problems here are solved.
