### ISSUE TITLE
Feature/Bug: Allow different config-files for deployment

### ISSUE THREAD

**Issue by TobiWo** [nomiclabs/buidler#737]
For compiling it is possible to use different buidler-configs. Unfortunately, this isn't possible for the deployment-process. I don't know whether this is a bug or it is intended behavior.

Note: I use Typescript instead of plain Javascript.

Command: `npx buidler --config buidler.config.one.ts --network myNetwork run scripts/deploy.ts`

Expected behavior:
Deploys the defined contracts.

Current behavior:
Buidler throws:
`BuidlerError: BDLR1: You are not inside a Buidler project.`

I read that you are working on a plugin with regards to different config files. Will this cover the mentioned issue?

**Comment by fvictorio** [comment]
You mean that `--config` works for `buidler compile` but not for `buidler run`? If that's the case, that sounds like a bug.

Is your repo public?

**Comment by fvictorio** [comment]
Tried this in a simple buidler project with typescript and I couldn't reproduce it, so we'll need more information.

I created a `buidler.config.ts` and a `buidler.config.alt.ts` and executed:

```
npx buidler compile
npx buidler --config buidler.config.alt.ts compile
npx buidler run scripts/script.ts
npx buidler --config buidler.config.alt.ts run scripts/script.ts
```

All of them worked.

**Comment by alcuadrado** [comment]
Can you provide a complete stack trace of the error?

**Comment by TobiWo** [comment]
Ok, sorry for the lazy issue description. I will extend this as you suggest.

> You mean that `--config` works for `buidler compile` but not for `buidler run`? If that's the case, that sounds like a bug.
> 
> Is your repo public?

Referring to your first question: Exactly, that's the case. Interesting that it is working on your side.
Referring to your second question: No, it is not a public repo and I cannot push it because it is for my company. If we cannot solve the issue with the information I'm providing I will push a similar repo to my account (if the error exists there as well). 

I also checked some more variations with multiple config-files and found some interesting behavior.

Let's start with my two config files:

1. buidler.config.alt1.ts

```
import { BuidlerConfig, usePlugin } from '@nomiclabs/buidler/config';

usePlugin("@nomiclabs/buidler-ethers");

const config: BuidlerConfig = {
    solc: {
        version: "0.6.6",
        optimizer: {
            enabled: true,
            runs: 200
        }
    },
    networks: {
        localDevEnvironment: {
            url: "http://localhost:8545",
            chainId: 101,
            from: "0x1c86ddf721cdcc47ecd854b477394661ddf57504",
            gas: "auto",
            gasPrice: 80000000000,
            timeout: 200
        }
    },
    paths: {
        sources: "./contracts/1",
        cache: "./cache/1",
        artifacts: "./artifacts/1"
    }
}

export default config;
```

2. buidler.config.alt2.ts

```
import { BuidlerConfig, usePlugin } from '@nomiclabs/buidler/config';

usePlugin("@nomiclabs/buidler-ethers");

const config: BuidlerConfig = {
    solc: {
        version: "0.4.24",
        optimizer: {
            enabled: false,
            runs: 200
        }
    },
    networks: {
        localDevEnvironment: {
            url: "http://localhost:8645",
            chainId: 101,
            from: "0xd5c3c36319984ef9e70a41fe1127b45b7ccdc005",
            gas: "auto",
            gasPrice: 80000000000,
            timeout: 200
        }
    },
    paths: {
        sources: "./contracts/2",
        cache: "./cache/2",
        artifacts: "./artifacts/2"
    }
}

export default config;
```

I don't know if it is of interest but here is my tsconfig.json as well:

```
{
    "compilerOptions": {
      "target": "es2020",
      "module": "commonjs",
      "strict": true,
      "esModuleInterop": true,
      "outDir": "dist",
      "forceConsistentCasingInFileNames": true,
      "sourceMap": true,
      "resolveJsonModule": true
    },
    "include": ["./scripts"],
    "files": [
      "./buidler.config.alt1.ts",
      "./buidler.config.alt2.ts",
      "./node_modules/@nomiclabs/buidler-ethers/src/type-extensions.d.ts",
    ]
}
```

Command
`npx buidler --config buidler.config.alt2.ts --network localDevEnvironment run scripts/deploy_2.ts`

1. If I rename `buidler.config.alt1.ts` to regulary `buidler.config.ts`, buidler always tries to use the `buidler.config.ts` instead of the `buidler.config.alt2.ts`. I'm getting error:

```
BuidlerError: BDLR700: Artifact for contract "Test" not found
```
That is correct because the contract isn't present. As you can see I used the path-properties in both config-files. That's where the error is coming from.

2. If I have both config files with different names, the error is the following:

```
C:\Users\...\node_modules\@nomiclabs\buidler\src\internal\core\project-structure.ts:30
    throw new BuidlerError(ERRORS.GENERAL.NOT_INSIDE_PROJECT);
          ^
BuidlerError: BDLR1: You are not inside a Buidler project.
    at Object.getUserConfigPath (C:\Users\...\node_modules\@nomiclabs\buidler\src\internal\core\project-structure.ts:30:11)
    at Object.loadConfigAndTasks (C:\Users\...\node_modules\@nomiclabs\buidler\src\internal\core\config\config-loading.ts:23:18)
    at Object.<anonymous> (C:\Users\...\node_modules\@nomiclabs\buidler\src\register.ts:35:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
```
If I checked the buidler core-code correctly I would assume that my config-parameter isn't recognized. The first described error (using one regulary named config and one with alternative name) supports this hypothesis.

See error from run with two different named config-files:
`at Object.loadConfigAndTasks (C:\Users\...\node_modules\@nomiclabs\buidler\src\internal\core\config\config-loading.ts:23:18)` Would you agree on that? Maybe you have an idea what I can change. Probably I have some bad configuration of the whole project.

Just as a reminder, using `--config` with the compile-parameter works as expected.

**Comment by fvictorio** [comment]
Thanks @TobiWo, I can reproduce it now. There are two bugs, although the underlying reason is probably the same:

- Using `buidler run --config buidler.config.alt2.ts` doesn't work if there is no `buidler.config.ts`
- Using `buidler run --config buidler.config.alt2.ts` uses `buidler.config.ts` if present, instead of the passed config.

And it seems like this behavior doesn't happen with `compile`.

**Comment by TobiWo** [comment]
Hi @fvictorio,

do you have a timetable when this bug could be fixed?

Best,
Tobi

**Comment by alcuadrado** [comment]
Thanks for the detailed report, @TobiWo! This is really helpful. 

We are currently focused on a couple of new features, and may not have time to take a look at this error this week. We'll discuss it internally and I'll get back to you soon.

**Comment by TobiWo** [comment]
Your welcome. If I find time I will probably check the code for myself. It's always nice to contribute.
If I'm not able to find the issue I'm looking forward for your solution 😃.
