### ISSUE TITLE
Feature Request:  `buidler node --fork` to fork from mainnet, Kovan, etc.

### ISSUE THREAD

**Issue by chanhosuh** [nomiclabs/buidler#742]
Are there any plans for a `buidler node --fork` option as with Ganache, e.g. `ganache-cli --fork=${NODE_URL}` where `NODE_URL` can be, for example, an Infura mainnet node?

Right now, due to lack of this feature, I don't see any way of doing integration testing with Buidler EVM, short of actually doing lengthy, complicated deploys of other people's contracts onto a local Buidler node.  I can of course just connect to Ganache, but then I'm not getting the cool Buidler EVM features like solidity stack traces, etc.

**Comment by alcuadrado** [comment]
Thanks for the suggestion! We are currently working on this. It will be released soon.

I'm closing this issue, but feel free to open new ones with further suggestions 🙌

**Comment by steffenix** [comment]
Same issue for me, will monitor this.

**Comment by alanwilhelm** [comment]
This would be great. Would love to use stacktrace on a mainnet fork.
