### ISSUE TITLE
typescript support detection fails when using pnpm

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/buidler#750]
[pnpm](https://pnpm.js.org) use a different folder structure for node_modules which allows it to be more strict : package that are not direct dependencies of the project are not visible 

This folder structure make buidler fails to detect typescript support. 

so when executing a package.json scruipt using buidler it trigger the buidler create project welcome screen as it cannot find buidler.config.js (even though buidler.config.ts is present)

**Comment by alcuadrado** [comment]
Hey @wighawag,

Thanks for reporting this. I'm pretty sure it is fixed by this PR: https://github.com/nomiclabs/buidler/pull/749 -- What do you think?

**Comment by wighawag** [comment]
Cool, looks like it will also allow pnpm to work, excelent!

**Comment by alcuadrado** [comment]
I'm closing this issue as #749 should fix it. Thanks @wighawag !

**Comment by wighawag** [comment]
I can confirm that it fixes the issue I had with pnpm

**Comment by wighawag** [comment]
But this fails in test setup like here : https://github.com/wighawag/buidler-ts-plugin-boilerplate/tree/buidler.config.ts
where test/buidler-project contains a buidler-config.ts

For this to work, I had to use BUIDLER_CONFIG env variable

I need set the env variable BUIDLER_CONFIG to the absolute path of the config file
if I use relative path the first test pass but later test consider the path relative to the test project, as opposed to the plugin root

**Comment by wighawag** [comment]
nevermind, found the issue, it was mocha setting that was importing the config file on its own
