### ISSUE TITLE
Error at HttpProvider.send "Error: The execution failed due to an exception." when trying to access Chainlink API's

### ISSUE THREAD

**Issue by shamb0** [nomiclabs/buidler#790]
Hello Everyone,

Facing some "Error: The execution failed due to an exception." when trying to access Chainlink Oracles/adopter API.

I am using "buidler" SDK and kovan testnet. normal testcases are passing except
test-cases trying to interact with chainlink oracles ( here I am using example from "https://docs.chain.link/docs/get-a-random-number#config" ). repo can be found here ("https://github.com/shamb0/cl-chg-2020-agem.git")

```shell
debug:deploy-contract Registering GEFMain with AddressResolver +0ms
  debug:deploy-contract Registered GEFMain with AddressResolver (0x1Bb4b92eFfa8772CaA71213CE059f9551A9Dfe90) +10s
  debug:GEFMain-Test Registered "CLIOManagerProxy" with AddressResolver (0xdFEA251B02AE23eCCf89cFECe25AD6C5a30f1b0C) +0ms
  debug:GEFMain-Test "CLIOManager address (0xf2B1935E9846f8129D8c7b7D5804498003a566eA) +0ms
    ✓ Register User Owner1 (12189ms)
    ✓ Register ECU Node (7870ms)
  mocha:runner total number of failures: 1 +3m
    1) Update ECU Status

  mocha:runner run(): root suite completed; emitting end +3ms

  2 passing (3m)
  1 failing

  1) GEFMain Test
       Update ECU Status:
     Error: The execution failed due to an exception.
      at HttpProvider.send (node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
      at wrapper_1.wrapSend (node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:149:21)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Like to know what can trigger this error, Will be helpfull to debug the issue together with chainlink team.

**buidler.config.ts**

![](https://i.imgur.com/EmXmT37.png)

**Comment by alcuadrado** [comment]
As mentioned on Discord, this error comes from a Parity node, and is not from Buidler, so I'm closing this issue.
