### ISSUE TITLE
buidler tests failing with solidity 0.7.0 Uncaught error outside test suite

### ISSUE THREAD

**Issue by alleycatdev** [nomiclabs/buidler#823]
https://cdn.discordapp.com/attachments/757623063767679087/760136783663988776/unknown.png

appears it is due to no longer requiring visibility on constructors(solidity-parser) failing to take into account the 0.7.0 changes.

**Comment by fvictorio** [comment]
That debug error might be misleading. It means that buidler falls back to using a regex. I think your problem is elsewhere.

The "Uncaught error outside test suite" comes from mocha. Maybe you can get more information if you do `DEBUG='*' npx buidler test`, that will include mocha internal logs too.

**Comment by alleycatdev** [comment]
no buidler node running is issue =/ derp

**Comment by fvictorio** [comment]
I see. It would be nice to show a better error message in that scenario, but I don't know if that's a buidler core issue or a buidler-deploy issue.

**Comment by fvictorio** [comment]
Just checked and, without `buidler-deploy`, a proper error is shown when buidler cannot connect to the network.

@wighawag does it make sense to open an issue for this in `buidler-deploy`?

**Comment by wighawag** [comment]
yes, sure. but what is the error and from where it happen ? is the related to the `node` task ?

**Comment by fvictorio** [comment]
If I understand correctly, it happens when tests are run against an HTTP node, and that node isn't connected. For example, doing `buidler node` and then `buidler test --network local`. I might have misunderstood though.
