### ISSUE TITLE
buidler tests throw warning for no visibility on constructors when using 0.7 solidity

### ISSUE THREAD

**Issue by alleycatdev** [nomiclabs/buidler#831]
`>>>>> WARNING <<<<<<
Failed to parse file: "./src/tokens/ElasticGovernanceToken.sol". No data will collected for its contract(s).
NB: some Solidity 0.6.x syntax is not supported by the JS parser yet.
Please report the error below to github.com/consensys/solidity-parser-antlr
>>>>>>>>>>>>>>>>>>>>
Error: Constructors have to be declared either "public" or "internal"`

I didn't report this to consensys because I know that @fvictorio maintains the parser now.

to recreate create a 0.7.x project and run a test.

**Comment by alcuadrado** [comment]
Hey @alleycatdev,

Can you tell us which plugins do you use?

Thanks!

**Comment by fvictorio** [comment]
Hey @alleycatdev, I just checked and that error comes from eth-gas-reporter ([line](https://github.com/cgewecke/eth-gas-reporter/blob/master/lib/utils.js#L133)). I'd suggest you open an issue or a PR in that repo for upgrading the parser.

Closing this for now, please re-open if there's something we can do on our side.
