### ISSUE TITLE
Property 'ethers' does not exist on type 'BuidlerRuntimeEnvironment'

### ISSUE THREAD

**Issue by isaacdchan** [nomiclabs/buidler#836]
Attempting to enable TS support. The default buidler.config.ts given does not work 

Offending Line - `const accounts = await bre.ethers.getSigners();`

**Comment by alcuadrado** [comment]
Hey, take a look at this: https://www.npmjs.com/package/@nomiclabs/buidler-ethers#typescript-support

**Comment by isaacdchan** [comment]
Ahh okay. I'd already included those two lines in my tsconfig but forgot to modify my node_modules path.

Thanks! Closing this issue

**Comment by alcuadrado** [comment]
Oh, I see. That config is kind of fragile, especially when using yarn. This will be improved in a release we are putting out in about 15 days.
