### ISSUE TITLE
It is posible to interact with existing contracts, like ganache fork?

### ISSUE THREAD

**Issue by jboadas** [nomiclabs/buidler#842]
This is more like a question, there is a way to interact with existing contracts like using

`ganache-cli --fork https://mainnet.infura.io/v3/<infura-key>`

I cannot find anything related on documentation.
Thanks.

**Comment by alcuadrado** [comment]
Not yet, it will be released soon.

**Comment by jboadas** [comment]
Thanks for your reply, nice to know, buidler console.log is an awesome tool
