### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by RobertoSnap** [nomiclabs/buidler#899]
Would it be possible to define hooks that other 3pt can utilize?

For example, I am creating a plugin that should run right after buidler-deploy has watched for changes and deployed. But right now I THINK my only possibility to hook into this process is to copy everything and override. 

It would be nice if buidler-deploy could state following in its watch process. 
```
await bre.run("deploy:before-watch-deploy")
await bre.run("deploy:after-watch-deploy")
```
Then I can create a task that runs when they execute. 

If I create a run that does not have a task i get this 
```
@symfoni/buidler-demo: BuidlerError: BDLR303: Unrecognized task deploy:before-before-watch-deploy
@symfoni/buidler-demo:     at Environment.run (/Users/robin/code/buidler-plugins/packages/buidler-demo/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:118:13)
@symfoni/buidler-demo:     at /Users/robin/code/buidler-plugins/packages/buidler-react/dist/src/index.js:55:23
@symfoni/buidler-demo:     at step (/Users/robin/code/buidler-plugins/packages/buidler-react/dist/src/index.js:33:23)
@symfoni/buidler-demo:     at Object.next (/Users/robin/code/buidler-plugins/packages/buidler-react/dist/src/index.js:14:53)
@symfoni/buidler-demo:     at fulfilled (/Users/robin/code/buidler-plugins/packages/buidler-react/dist/src/index.js:5:58)
@symfoni/buidler-demo:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by fvictorio** [comment]
Hey @RobertoSnap, if this is specifically about `buidler-deploy`, I suggest you open the issue in its repo: https://github.com/wighawag/buidler-deploy/

**Comment by RobertoSnap** [comment]
@fvictorio Yea, but it required a change with error message BDLR303 as if buidler-deploy creates hooks without task it will give an error for everyone not implementing that.

its spesifically the code in https://github.com/nomiclabs/buidler/blob/development/packages/buidler-core/src/internal/core/runtime-environment.ts :103

```typescript
/**
   * Executes the task with the given name.
   *
   * @param name The task's name.
   * @param taskArguments A map of task's arguments.
   *
   * @throws a BDLR303 if there aren't any defined tasks with the given name.
   * @returns a promise with the task's execution result.
   */
  public readonly run: RunTaskFunction = async (name, taskArguments = {}) => {
    const taskDefinition = this.tasks[name];

    log("Running task %s", name);

    if (taskDefinition === undefined) {
      throw new BuidlerError(ERRORS.ARGUMENTS.UNRECOGNIZED_TASK, {
        task: name,
      });
    }

    const resolvedTaskArguments = this._resolveValidTaskArguments(
      taskDefinition,
      taskArguments
    );

    return this._runTaskDefinition(taskDefinition, resolvedTaskArguments);
  };
```

I assume there is a reason for this error message. But if not, I'm asking if we can remove it.

**Comment by alcuadrado** [comment]
@RobertoSnap, that's not necessary and would break the task system, silently failing in lots of cases. What buidler-deploy should do is creating empty tasks to give its users the opportunity to override them.

**Comment by RobertoSnap** [comment]
ok, thank you. Will post this inn buidler-deploy.
